version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: pgsql_db
    restart: always
    environment:
      POSTGRES_DB: produit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zakaria
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
